### PR TITLE
DOC-7231: Change in behaviour of indexer stats rest endpoint

### PR DESCRIPTION
**Pull request by simon-dew**
The following draft documentation is ready for review:

[Index Statistics API](https://simon-dew.github.io/docs-site/DOC-7231/server/7.0/rest-api/rest-index-stats.html)

Docs issue: [DOC-7231](https://issues.couchbase.com/browse/DOC-7231)

### CODE REVIEW

**Comment by VarunVelamuri** [comment]
@simon-dew, This endpoint started to support RBAC from 7.0. So, this is not entirely true: "Users must have Cluster Read and Bucket INDEX List privileges."

The behaviour is as follows:

a. If user has "Query System Catalog" permissions, then all the stats will be returned. This includes node level stats like indexer state, memory_quota etc.
b. If user has bucket/scope/collection level permissions only, then only the stats for that bucket/scope/collection level will be returned
E.g., if a user has RBAC permissions set only for "default" bucket, "_test" scope, "_test" collection, then if the user queries "api/v1/stats" (or) "api/v1/stats/default" or "api/v1/stats/default._test" or "api/v1/stats/default._test._test" will return the same output i.e. stats of all indexes in "default" bucket, "_test" scope, "_test" collection

**Comment by simon-dew** [comment]
> a. If user has "Query System Catalog" permissions, then all the stats will be returned. This includes node level stats like indexer state, memory_quota etc.
> b. If user has bucket/scope/collection level permissions only, then only the stats for that bucket/scope/collection level will be returned

Done

**Comment by simon-dew** [comment]
> The Security section needs more work.

Done

**Comment by VarunVelamuri** [comment]
@simon-dew Looks good to me.

**Review by deepkaran — APPROVED** [review]

**Review by ksaikrishnateja — APPROVED** [review]
Checked the Security part at the end. Looks good to me too.

**Pull request merged**
