### PR TITLE
DOC-10867: Add use replica parameter

### PR DESCRIPTION
**Pull request by simon-dew**
Docs issue: DOC-10867

Added read replica parameters to Query Settings, Query Admin, and Query Service REST APIs. Also migrated the spec markup language from AsciiDoc to Markdown for future compatibility with Redocly.

Docs preview:

* [Query Settings REST API](https://ia.docs-test.couchbase.com/server/current/rest-api/rest-cluster-query-settings.html#queryUseReplica)
* [Query Admin REST API](https://ia.docs-test.couchbase.com/server/current/n1ql/n1ql-rest-api/admin.html#use-replica-srv)
* [Query Service REST API](https://ia.docs-test.couchbase.com/server/current/n1ql/n1ql-rest-api/index.html#use_replica_req)
* [Login details](https://couchbasecloud.atlassian.net/l/cp/2GtKM5Pr) &mdash; see IA Build

Linked pull requests:

* Settings and Parameters: https://github.com/couchbase/docs-server/pull/3401

### CODE REVIEW

**Review by dhanyagowrish — CHANGES_REQUESTED** [review]
The content of the Cluster level, Node level and Request level settings for read from replica look good to me. 

However, there are two points in DOC-10867 's description that I could not find in the PR and that should be added:

1. Reading from replica is only possible if the cluster is on version 7.6.0 or higher. 

2. Even if use replica is turned on for a query, if the query uses the Sequential Scan index, and a data node goes down, the query might return with an error. This is because, currently, KV range scans cannot be started on replica v buckets.

**Review by dhanyagowrish — CHANGES_REQUESTED** [review]
In the Cluster, Node, Request level descriptions for read from replica, could we please make a change here
Rather than -
SELECT queries within a transaction cannot read from replica.

It should be - Only SELECT queries that are not within a transaction can read from replica.

( Because the earlier statement implies that non-SELECT queries can read from replica. Which is not true. )

**Comment by simon-dew** [comment]
> Only SELECT queries that are not within a transaction can read from replica

Done

**Comment by simon-dew** [comment]
> * Reading from replica is only possible if the cluster is on version 7.6.0 or higher.

Done

> * Even if use replica is turned on for a query, if the query uses the Sequential Scan index, and a data node goes down, the query might return with an error. This is because, currently, KV range scans cannot be started on replica v buckets.

Done

**Pull request merged**
